Add Grades feature
OSU-MC/MyClassroom pull request #229
Opened 2024-05-22 18:56 UTC by Justin-Fernbaugh

# Pull Request Template

## Screenshots

## Description
I've added a Grades table that populates or updates the grades of a user after they respond to a question(Responses.js). Moreover, these changes involve using points that are added to questions using the 'weights' attribute of a question. The 'weights' of a question can be added or if they're not present will be auto-populated with a default value of '1' for each.

Important: before testing this branch the databases have to be dropped, re-added, and then migrated/seeded. The first four steps must be performed in MySQL while steps 5-8 are performed in the dir server/
1. DROP DATABASE myclassroom_development;
2. CREATE DATABASE myclassroom_development;
3. DROP DATABASE myclassroom_test;
4. CREATE DATABASE myclassroom_test;
5. npx sequelize-cli db:migrate --env test
6. npx sequelize-cli db:migrate --env dev
7. npx sequelize-cli db:seed:all --env test
8. npx sequelize-cli db:seed:all --env dev

Fixes # (issue)

## Additional Information

## Checklist:
Before you submit your Pull Request, please make sure you have completed the following tasks:
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] New and existing unit tests pass locally with my changes.
- [X] Any dependent changes have been merged and published in downstream modules.
- [X] I have tagged my PR with the appropriate label(s).

2024-05-22 20:56 UTC, Justin-Fernbaugh commented on server/app/api/users.js
> +});
@karinocheretny Did you happen to get this same alert on your user changes? I assume its from when I merged dev into this branch

2024-05-23 21:59 UTC, nilsstreedain requested changes
Looks like this PR has the same issue that @Durbin-Elijah's did. If you remember, awhile back, we had an unknown contributor who made a PR to `main` that got accepted, causing divergent history between `main`/`dev` because all changes on `main` were intended to come directly from `dev`, nowhere else. It appears the branch submitted in this PR was pulled from `main` instead of `dev` causing it to try to merge those non-existent commits to `dev`. Would it be possible to go through and remove any commits that are not apart of this change so once we are ready for a new version, I can force override `main`? (Only force overriding because our branches should be built from `dev`, not `main`.)

2024-05-23 22:18 UTC, Justin-Fernbaugh commented
> Looks like this PR has the same issue that @Durbin-Elijah's did. If you remember, awhile back, we had an unknown contributor who made a PR to `main` that got accepted, causing divergent history between `main`/`dev` because all changes on `main` were intended to come directly from `dev`, nowhere else. It appears the branch submitted in this PR was pulled from `main` instead of `dev` causing it to try to merge those non-existent commits to `dev`. Would it be possible to go through and remove any commits that are not apart of this change so once we are ready for a new version, I can force override `main`? (Only force overriding because our branches should be built from `dev`, not `main`.)

Yeah, I should be able to do this, would you be able to point me to which commit this starts so I can remove the changes?

2024-05-24 00:08 UTC, nilsstreedain commented
> > Looks like this PR has the same issue that @Durbin-Elijah's did. If you remember, awhile back, we had an unknown contributor who made a PR to `main` that got accepted, causing divergent history between `main`/`dev` because all changes on `main` were intended to come directly from `dev`, nowhere else. It appears the branch submitted in this PR was pulled from `main` instead of `dev` causing it to try to merge those non-existent commits to `dev`. Would it be possible to go through and remove any commits that are not apart of this change so once we are ready for a new version, I can force override `main`? (Only force overriding because our branches should be built from `dev`, not `main`.)
> 
> Yeah, I should be able to do this, would you be able to point me to which commit this starts so I can remove the changes?

Looks like just commits c6524de, 86d4753, and 5ed0d93 need to be removed, preferably with a rebase. If anything is left committing to `/client`, that should also probably be removed.

2024-05-26 20:12 UTC, Justin-Fernbaugh commented
Merged with changes from dev and dropped any changes from main. Ready for a second look

2024-05-26 20:56 UTC, nilsstreedain requested changes
Generally looks great, see comments for 2 minor changes I found.

2024-05-26 20:56 UTC, nilsstreedain commented on server/.env.example
Merge conflict remnants

2024-05-26 20:56 UTC, nilsstreedain commented on .gitignore
> +/client/node_modules
Duplicate line

2024-05-26 21:20 UTC, Justin-Fernbaugh commented on .gitignore
> +/client/node_modules
Pushed

2024-05-26 21:20 UTC, Justin-Fernbaugh commented on server/.env.example
Pushed

2024-05-26 21:25 UTC, nilsstreedain submitted a review, later dismissed
Looks great!

2024-05-26 21:29 UTC, nilsstreedain approved these changes
Looks great, nice job!

2024-05-26 21:49 UTC, merged